export default function Head() {
  return (
    <>
      <title>Mi NextJS 13 app</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="stylesheet" type="text/css" href="global.css" />
    </>
  );
}
